services:
  postgres-db:
    image: postgres:18-bookworm
    container_name: db_economico
    environment:
      POSTGRES_USER: dados_admin
      POSTGRES_PASSWORD: 39728651@Dd
      POSTGRES_DB: economia_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql